/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as Authorizable from './generated-artifacts/Authorizable.json';
import * as AuthorizableV06 from './generated-artifacts/AuthorizableV06.json';
import * as AuthorizableV08 from './generated-artifacts/AuthorizableV08.json';
import * as D18 from './generated-artifacts/D18.json';
import * as DeploymentConstants from './generated-artifacts/DeploymentConstants.json';
import * as IAuthorizable from './generated-artifacts/IAuthorizable.json';
import * as IAuthorizableV06 from './generated-artifacts/IAuthorizableV06.json';
import * as IAuthorizableV08 from './generated-artifacts/IAuthorizableV08.json';
import * as IOwnable from './generated-artifacts/IOwnable.json';
import * as IOwnableV06 from './generated-artifacts/IOwnableV06.json';
import * as IOwnableV08 from './generated-artifacts/IOwnableV08.json';
import * as LibAddress from './generated-artifacts/LibAddress.json';
import * as LibAddressArray from './generated-artifacts/LibAddressArray.json';
import * as LibAddressArrayRichErrors from './generated-artifacts/LibAddressArrayRichErrors.json';
import * as LibAuthorizableRichErrors from './generated-artifacts/LibAuthorizableRichErrors.json';
import * as LibAuthorizableRichErrorsV06 from './generated-artifacts/LibAuthorizableRichErrorsV06.json';
import * as LibAuthorizableRichErrorsV08 from './generated-artifacts/LibAuthorizableRichErrorsV08.json';
import * as LibBytes from './generated-artifacts/LibBytes.json';
import * as LibBytesRichErrors from './generated-artifacts/LibBytesRichErrors.json';
import * as LibBytesRichErrorsV06 from './generated-artifacts/LibBytesRichErrorsV06.json';
import * as LibBytesRichErrorsV08 from './generated-artifacts/LibBytesRichErrorsV08.json';
import * as LibBytesV06 from './generated-artifacts/LibBytesV06.json';
import * as LibBytesV08 from './generated-artifacts/LibBytesV08.json';
import * as LibEIP1271 from './generated-artifacts/LibEIP1271.json';
import * as LibEIP712 from './generated-artifacts/LibEIP712.json';
import * as LibFractions from './generated-artifacts/LibFractions.json';
import * as LibMath from './generated-artifacts/LibMath.json';
import * as LibMathRichErrors from './generated-artifacts/LibMathRichErrors.json';
import * as LibMathRichErrorsV06 from './generated-artifacts/LibMathRichErrorsV06.json';
import * as LibMathRichErrorsV08 from './generated-artifacts/LibMathRichErrorsV08.json';
import * as LibMathV06 from './generated-artifacts/LibMathV06.json';
import * as LibMathV08 from './generated-artifacts/LibMathV08.json';
import * as LibOwnableRichErrors from './generated-artifacts/LibOwnableRichErrors.json';
import * as LibOwnableRichErrorsV06 from './generated-artifacts/LibOwnableRichErrorsV06.json';
import * as LibOwnableRichErrorsV08 from './generated-artifacts/LibOwnableRichErrorsV08.json';
import * as LibReentrancyGuardRichErrors from './generated-artifacts/LibReentrancyGuardRichErrors.json';
import * as LibReentrancyGuardRichErrorsV06 from './generated-artifacts/LibReentrancyGuardRichErrorsV06.json';
import * as LibReentrancyGuardRichErrorsV08 from './generated-artifacts/LibReentrancyGuardRichErrorsV08.json';
import * as LibRichErrors from './generated-artifacts/LibRichErrors.json';
import * as LibRichErrorsV06 from './generated-artifacts/LibRichErrorsV06.json';
import * as LibRichErrorsV08 from './generated-artifacts/LibRichErrorsV08.json';
import * as LibSafeMath from './generated-artifacts/LibSafeMath.json';
import * as LibSafeMathRichErrors from './generated-artifacts/LibSafeMathRichErrors.json';
import * as LibSafeMathRichErrorsV06 from './generated-artifacts/LibSafeMathRichErrorsV06.json';
import * as LibSafeMathRichErrorsV08 from './generated-artifacts/LibSafeMathRichErrorsV08.json';
import * as LibSafeMathV06 from './generated-artifacts/LibSafeMathV06.json';
import * as Ownable from './generated-artifacts/Ownable.json';
import * as OwnableV06 from './generated-artifacts/OwnableV06.json';
import * as OwnableV08 from './generated-artifacts/OwnableV08.json';
import * as ReentrancyGuard from './generated-artifacts/ReentrancyGuard.json';
import * as ReentrancyGuardV06 from './generated-artifacts/ReentrancyGuardV06.json';
import * as ReentrancyGuardV08 from './generated-artifacts/ReentrancyGuardV08.json';
import * as Refundable from './generated-artifacts/Refundable.json';
import * as TestAuthorizable from './generated-artifacts/TestAuthorizable.json';
import * as TestLibAddress from './generated-artifacts/TestLibAddress.json';
import * as TestLibAddressArray from './generated-artifacts/TestLibAddressArray.json';
import * as TestLibBytes from './generated-artifacts/TestLibBytes.json';
import * as TestLibEIP712 from './generated-artifacts/TestLibEIP712.json';
import * as TestLibMath from './generated-artifacts/TestLibMath.json';
import * as TestLibRichErrors from './generated-artifacts/TestLibRichErrors.json';
import * as TestLibSafeMath from './generated-artifacts/TestLibSafeMath.json';
import * as TestLogDecoding from './generated-artifacts/TestLogDecoding.json';
import * as TestLogDecodingDownstream from './generated-artifacts/TestLogDecodingDownstream.json';
import * as TestOwnable from './generated-artifacts/TestOwnable.json';
import * as TestReentrancyGuard from './generated-artifacts/TestReentrancyGuard.json';
import * as TestRefundable from './generated-artifacts/TestRefundable.json';
import * as TestRefundableReceiver from './generated-artifacts/TestRefundableReceiver.json';
export const artifacts = {
    Authorizable: Authorizable as ContractArtifact,
    D18: D18 as ContractArtifact,
    DeploymentConstants: DeploymentConstants as ContractArtifact,
    LibAddress: LibAddress as ContractArtifact,
    LibAddressArray: LibAddressArray as ContractArtifact,
    LibAddressArrayRichErrors: LibAddressArrayRichErrors as ContractArtifact,
    LibAuthorizableRichErrors: LibAuthorizableRichErrors as ContractArtifact,
    LibBytes: LibBytes as ContractArtifact,
    LibBytesRichErrors: LibBytesRichErrors as ContractArtifact,
    LibEIP1271: LibEIP1271 as ContractArtifact,
    LibEIP712: LibEIP712 as ContractArtifact,
    LibFractions: LibFractions as ContractArtifact,
    LibMath: LibMath as ContractArtifact,
    LibMathRichErrors: LibMathRichErrors as ContractArtifact,
    LibOwnableRichErrors: LibOwnableRichErrors as ContractArtifact,
    LibReentrancyGuardRichErrors: LibReentrancyGuardRichErrors as ContractArtifact,
    LibRichErrors: LibRichErrors as ContractArtifact,
    LibSafeMath: LibSafeMath as ContractArtifact,
    LibSafeMathRichErrors: LibSafeMathRichErrors as ContractArtifact,
    Ownable: Ownable as ContractArtifact,
    ReentrancyGuard: ReentrancyGuard as ContractArtifact,
    Refundable: Refundable as ContractArtifact,
    IAuthorizable: IAuthorizable as ContractArtifact,
    IOwnable: IOwnable as ContractArtifact,
    AuthorizableV06: AuthorizableV06 as ContractArtifact,
    LibBytesV06: LibBytesV06 as ContractArtifact,
    LibMathV06: LibMathV06 as ContractArtifact,
    LibSafeMathV06: LibSafeMathV06 as ContractArtifact,
    OwnableV06: OwnableV06 as ContractArtifact,
    ReentrancyGuardV06: ReentrancyGuardV06 as ContractArtifact,
    LibAuthorizableRichErrorsV06: LibAuthorizableRichErrorsV06 as ContractArtifact,
    LibBytesRichErrorsV06: LibBytesRichErrorsV06 as ContractArtifact,
    LibMathRichErrorsV06: LibMathRichErrorsV06 as ContractArtifact,
    LibOwnableRichErrorsV06: LibOwnableRichErrorsV06 as ContractArtifact,
    LibReentrancyGuardRichErrorsV06: LibReentrancyGuardRichErrorsV06 as ContractArtifact,
    LibRichErrorsV06: LibRichErrorsV06 as ContractArtifact,
    LibSafeMathRichErrorsV06: LibSafeMathRichErrorsV06 as ContractArtifact,
    IAuthorizableV06: IAuthorizableV06 as ContractArtifact,
    IOwnableV06: IOwnableV06 as ContractArtifact,
    AuthorizableV08: AuthorizableV08 as ContractArtifact,
    LibBytesV08: LibBytesV08 as ContractArtifact,
    LibMathV08: LibMathV08 as ContractArtifact,
    OwnableV08: OwnableV08 as ContractArtifact,
    ReentrancyGuardV08: ReentrancyGuardV08 as ContractArtifact,
    LibAuthorizableRichErrorsV08: LibAuthorizableRichErrorsV08 as ContractArtifact,
    LibBytesRichErrorsV08: LibBytesRichErrorsV08 as ContractArtifact,
    LibMathRichErrorsV08: LibMathRichErrorsV08 as ContractArtifact,
    LibOwnableRichErrorsV08: LibOwnableRichErrorsV08 as ContractArtifact,
    LibReentrancyGuardRichErrorsV08: LibReentrancyGuardRichErrorsV08 as ContractArtifact,
    LibRichErrorsV08: LibRichErrorsV08 as ContractArtifact,
    LibSafeMathRichErrorsV08: LibSafeMathRichErrorsV08 as ContractArtifact,
    IAuthorizableV08: IAuthorizableV08 as ContractArtifact,
    IOwnableV08: IOwnableV08 as ContractArtifact,
    TestAuthorizable: TestAuthorizable as ContractArtifact,
    TestLibAddress: TestLibAddress as ContractArtifact,
    TestLibAddressArray: TestLibAddressArray as ContractArtifact,
    TestLibBytes: TestLibBytes as ContractArtifact,
    TestLibEIP712: TestLibEIP712 as ContractArtifact,
    TestLibMath: TestLibMath as ContractArtifact,
    TestLibRichErrors: TestLibRichErrors as ContractArtifact,
    TestLibSafeMath: TestLibSafeMath as ContractArtifact,
    TestLogDecoding: TestLogDecoding as ContractArtifact,
    TestLogDecodingDownstream: TestLogDecodingDownstream as ContractArtifact,
    TestOwnable: TestOwnable as ContractArtifact,
    TestReentrancyGuard: TestReentrancyGuard as ContractArtifact,
    TestRefundable: TestRefundable as ContractArtifact,
    TestRefundableReceiver: TestRefundableReceiver as ContractArtifact,
};
